/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_teskalabs_seacat_android_client_core_seacatcc */

#ifndef _Included_com_teskalabs_seacat_android_client_core_seacatcc
#define _Included_com_teskalabs_seacat_android_client_core_seacatcc
#ifdef __cplusplus
extern "C" {
#endif
#undef com_teskalabs_seacat_android_client_core_seacatcc_RC_OK
#define com_teskalabs_seacat_android_client_core_seacatcc_RC_OK 0L
#undef com_teskalabs_seacat_android_client_core_seacatcc_RC_E_GENERIC
#define com_teskalabs_seacat_android_client_core_seacatcc_RC_E_GENERIC -9999L
/*
 * Class:     com_teskalabs_seacat_android_client_core_seacatcc
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/teskalabs/seacat/android/client/core/Reactor;)I
 */
JNIEXPORT jint JNICALL Java_com_teskalabs_seacat_android_client_core_seacatcc_init
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject);

/*
 * Class:     com_teskalabs_seacat_android_client_core_seacatcc
 * Method:    run
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_teskalabs_seacat_android_client_core_seacatcc_run
  (JNIEnv *, jclass);

/*
 * Class:     com_teskalabs_seacat_android_client_core_seacatcc
 * Method:    shutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_teskalabs_seacat_android_client_core_seacatcc_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_teskalabs_seacat_android_client_core_seacatcc
 * Method:    yield
 * Signature: (C)I
 */
JNIEXPORT jint JNICALL Java_com_teskalabs_seacat_android_client_core_seacatcc_yield
  (JNIEnv *, jclass, jchar);

/*
 * Class:     com_teskalabs_seacat_android_client_core_seacatcc
 * Method:    state
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_teskalabs_seacat_android_client_core_seacatcc_state
  (JNIEnv *, jclass);

/*
 * Class:     com_teskalabs_seacat_android_client_core_seacatcc
 * Method:    ppkgen_worker
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_teskalabs_seacat_android_client_core_seacatcc_ppkgen_1worker
  (JNIEnv *, jclass);

/*
 * Class:     com_teskalabs_seacat_android_client_core_seacatcc
 * Method:    csrgen_worker
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_teskalabs_seacat_android_client_core_seacatcc_csrgen_1worker
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_teskalabs_seacat_android_client_core_seacatcc
 * Method:    set_proxy_server_worker
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_teskalabs_seacat_android_client_core_seacatcc_set_1proxy_1server_1worker
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_teskalabs_seacat_android_client_core_seacatcc
 * Method:    time
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_teskalabs_seacat_android_client_core_seacatcc_time
  (JNIEnv *, jclass);

/*
 * Class:     com_teskalabs_seacat_android_client_core_seacatcc
 * Method:    log_set_mask
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_teskalabs_seacat_android_client_core_seacatcc_log_1set_1mask
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_teskalabs_seacat_android_client_core_seacatcc
 * Method:    socket_configure_worker
 * Signature: (ICCILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_teskalabs_seacat_android_client_core_seacatcc_socket_1configure_1worker
  (JNIEnv *, jclass, jint, jchar, jchar, jint, jstring, jstring);

/*
 * Class:     com_teskalabs_seacat_android_client_core_seacatcc
 * Method:    client_id
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_teskalabs_seacat_android_client_core_seacatcc_client_1id
  (JNIEnv *, jclass);

/*
 * Class:     com_teskalabs_seacat_android_client_core_seacatcc
 * Method:    client_tag
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_teskalabs_seacat_android_client_core_seacatcc_client_1tag
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
